document.getElementById("icon-link-student").addEventListener("click",function(){
    window.location.href="view_student.php";
})
document.getElementById("title-link-student").addEventListener("click",function(){
    window.location.href="view_student.php";
})
document.getElementById("icon-link-teacher").addEventListener("click",function(){
    window.location.href="view_infor_teacher.php";
})
document.getElementById("title-link-teacher").addEventListener("click",function(){
    window.location.href="view_infor_teacher.php";
})
document.getElementById("icon-link-profile").addEventListener("click",function(){
    window.location.href="view_profile.php";
})
document.getElementById("title-link-profile").addEventListener("click",function(){
    window.location.href="view_profile.php";
})
document.getElementById("icon-link-fee").addEventListener("click",function(){
    window.location.href="view_financial.php";
})
document.getElementById("title-link-fee").addEventListener("click",function(){
    window.location.href="view_financial.php";
})
document.getElementById("icon-link-schedule").addEventListener("click",function(){
    window.location.href="view_schedule.php";
})
document.getElementById("title-link-schedule").addEventListener("click",function(){
    window.location.href="view_schedule.php";
})
document.getElementById("icon-link-result").addEventListener("click",function(){
    window.location.href="view_result.php";
})
document.getElementById("title-link-result").addEventListener("click",function(){
    window.location.href="view_result.php";
})

